import {defaultThemeConfig} from '@/lib/theme-config'
import {ThemeConfigProvider} from '@/lib/theme-context'
import {generateHtmlClassNames} from '@/lib/theme-utils'
import type {Metadata} from 'next'
import {Barlow} from 'next/font/google'
import {cookies} from 'next/headers'
import './globals.css'

const font = Barlow({weight: ['300', '400', '500', '600', '700', '800'], subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const themeConfigCookie = cookies().get('themeConfig')
  const initialConfig = themeConfigCookie ? JSON.parse(themeConfigCookie.value) : defaultThemeConfig
  const htmlClassName = generateHtmlClassNames(initialConfig)
  return (
    <ThemeConfigProvider initialConfig={initialConfig}>
      <html lang="en" className={`${htmlClassName}`}>
        <body className={`bg-main-50 text-main-800 dark:bg-main-200 ${font.className}`}>{children}</body>
      </html>
    </ThemeConfigProvider>
  )
}
